import numpy as np
qsdr_2mm_trk_header = np.array(
        ('TRACK', [79, 95, 69], [2.0, 2.0, 2.0], 
         [0.0, 0.0, 0.0], 0, 
         ['', '', '', '', '', '', '', '', '', ''], 0, 
         ['', '', '', '', '', '', '', '', '', ''], 
         [[-2.0, 0.0, 0.0, 0.0], [0.0, -2.0, 0.0, 0.0], 
          [0.0, 0.0, -2.0, 0.0], [0.0, 0.0, 0.0, 1.0]], 
         '', 'LPS', 'LPS', [1.0, 0.0, 0.0, 0.0, 1.0, 0.0], 
         '', '', '', '', '', '', '', 100000, 2, 1000), 
      dtype=[('id_string', 'S6'), ('dim', '<i2', (3,)), 
             ('voxel_size', '<f4', (3,)), 
             ('origin', '<f4', (3,)), 
             ('n_scalars', '<i2'), ('scalar_name', 'S20', (10,)), 
             ('n_properties', '<i2'), ('property_name', 'S20', (10,)), 
             ('vox_to_ras', '<f4', (4, 4)), ('reserved', 'S444'), 
             ('voxel_order', 'S4'), ('pad2', 'S4'), 
             ('image_orientation_patient', '<f4', (6,)), 
             ('pad1', 'S2'), ('invert_x', 'S1'), ('invert_y', 'S1'), 
             ('invert_z', 'S1'), ('swap_xy', 'S1'), ('swap_yz', 'S1'), 
             ('swap_zx', 'S1'), ('n_count', '<i4'), ('version', '<i4'), 
             ('hdr_size', '<i4')])
